version: '3.6'
networks:
  talk:
    external: false

services:
  web:
    image: nginx:latest
    ports:
      - '3327:80'
    volumes:
      - ./api:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
      - talk
    depends_on:
      - php-fpm
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3336:3306'
    networks:
      - talk
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: talk
    depends_on:
      - php-fpm
  php-fpm:
    image: php:fpm
    volumes:
      - ./api:/var/www/html
      - ./api/composer.json:/var/www/html/composer.json
      - ./docker/commands.sh:/var/www/html/commands.sh
    networks:
      - talk
